#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u Hyper_parameter_tunning.py "$@"
python -u Training.py "$@"